image: node

stages:
  - lint

cache:
  key: node_modules
  paths:
    - node_modules/

eslint:
  stage: lint
  script: 
    - npm i eslint
    - npx eslint .
  only:
    - merge_requests
    - pushes
